spring:
  datasource:
    url: jdbc:h2:mem:gameofthreeDB
    driverClassName: org.h2.Driver
    username: justeattakeaway
    passowrd: 'juste@tTake@way'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8081

custom:
  app:
    util:
      start_number: 50
      end_number: 100
